const fs = require('fs');
let content = fs.readFileSync('App.tsx', 'utf8');
content = content.replace(/text-ink/g, 'text-ink dark:text-white');
content = content.replace(/border-line/g, 'border-line dark:border-gray-800');
content = content.replace(/bg-gray-50/g, 'bg-gray-50 dark:bg-gray-800/50');
content = content.replace(/bg-gray-100/g, 'bg-gray-100 dark:bg-gray-800');
content = content.replace(/text-gray-900/g, 'text-gray-900 dark:text-gray-100');
content = content.replace(/text-gray-800/g, 'text-gray-800 dark:text-gray-200');
content = content.replace(/text-gray-600/g, 'text-gray-600 dark:text-gray-300');
content = content.replace(/text-gray-500/g, 'text-gray-500 dark:text-gray-400');
fs.writeFileSync('App.tsx', content);
console.log('Replacements done.');
